typeReplacements:
    'PASTA/NOODLES': 'PASTA'
    'MAC & CHEESE': 'PASTA'
    'RICE/RICE MIX': 'RICE'
    'GRAVY/SAUCE': 'SAUCES'
    'BREAD': 'SLICED BREAD'

manufacturerToClass:
    'Swiss Miss': 'CHOCOLATE'
    'Nesquik': 'CHOCOLATE'
    'Ovaltine': 'CHOCOLATE'
    'Mahatma': 'RICE'
    'Soft & Precious': 'PERSONAL HYGIENE'
    'Crest': 'PERSONAL HYGIENE'
    'Stubbs': 'SAUCES'
    'Sunny Delight Drinks': 'JUICE'
    'Sunny D': 'JUICE'
    'Welchs': 'JUICE'
    'Powerade': 'FLAVORED DRINKS'
    'Capri Sun': 'FLAVORED DRINKS'
    'Lipton': 'FLAVORED DRINKS'
    'Nestea': 'FLAVORED DRINKS'
    'Minute Maid': 'JUICE'
    'Hawaiian Punch': 'FLAVORED DRINKS'
    'Morton': 'SPICES'
    'Campbells': 'SOUP'
    'Snapple': 'FLAVORED DRINKS'
    'Sparkling ICE': 'FLAVORED DRINKS'
    'Pringles': 'CHIPS'
    'Clorox': 'CLEANERS'
    'Scotch-Brite': 'CLEANERS'
    'Kool Aid': 'FLAVORED DRINKS'
    'Orville Redenbachers': 'POPCORN'
    'Produce': 'FRESH VEGETABLES'
    'Big K': 'SODA'
    'Sargento': 'CHEESE'
    'Oxi Clean': 'CLEANERS'
    'Palmolive': 'DISH SOAP'
    'Chef Boyardee': 'PASTA'
    'All': 'CLEANERS'
    'Lean Cusine': 'TV DINNER'
    'Reeses': 'CHOCOLATE CANDY'
    'Pediacare': 'COLD REMEDIES'
    'Carnation': 'FLAVORED DRINKS'
    'Classico': 'SAUCES'
    'Febreze': 'DEODORIZERS'
    'Entenmanns': 'COOKIES'
    'Little Debbie': 'COOKIES'
    'Tastykake': 'COOKIES'
    'Hostess': 'COOKIES'
    'Drakes': 'COOKIES'
    'All But Gluten': 'COOKIES'
    'Pepperidge Farm': 'SLICED BREAD'
    'Hershey': 'SAUCES'
    'Hersheys': 'SAUCES'
    'Heinz': 'SAUCES'
    'Motrin Infant': 'IBUPROFEN'
    'Nestle': 'FLAVORED DRINKS'
    'Jumex': 'FLAVORED DRINKS'
    'Gatorade': 'FLAVORED DRINKS'
    'Got Milk': 'FLAVORED DRINKS'
    "Stouffer's": 'TV DINNER'
    'Starkist': 'TUNA'
    'Banquet': 'TV DINNER'
    'On Cor': 'TV DINNER'
    'Lean Pockets': 'TV DINNER'
    'Koch Foods': 'TV DINNER'
    'Barber': 'TV DINNER'
    'Atkins': 'TV DINNER'
    'Aidells': 'TV DINNER'
    'Al Fresco': 'TV DINNER'
    'Dole': 'BANANAS'
    'Listerine': 'MOUTHWASH'
    'Little Noses': 'NASAL SPRAYS'
    'Mrs. Buttersworths': 'SAUCES'
    'Motts': 'SAUCES'
    'Country Time': 'FLAVORED DRINKS'
    'Oregon': 'CANNED FRUIT'
    'King Arthur': 'SPICES'
    'Alpine': 'FLAVORED DRINKS'
    'Act II': 'SAUCES'
    'Idahoan': 'FROZEN VEGETABLES'
    'Gefen': 'SPICES'
    'Con Agar Foods': 'FROZEN VEGETABLES'
    'Nutella': 'PEANUT BUTTER'
    
productNameToClass:
    'cookie': 'COOKIES'
    'bagel': 'BAGELS'
    'guacamole': 'DIPS'
    'cocoa': 'CHOCOLATE'
    'donut': 'DONUTS'
    'muffin': 'MUFFINS'
    'eggs': 'EGGS'
    'juice': 'JUICE'
    'pretzel': 'PRETZELS'
    'wheat thins': 'CRACKERS'
    'chips ahoy': 'COOKIES'
    'lays poppables': 'CHIPS'
    'lays stax': 'CHIPS'
    'lays variety': 'CHIPS'
    'stew': 'SOUP'
    'doritos': 'CHIPS'
    'kettle': 'CHIPS'
    'ruffles': 'CHIPS'
    'lays dip': 'DIPS'
    'tostitos dip': 'DIPS'
    'tostitos cantina': 'CHIPS'
    'tostitos bite': 'CHIPS'
    'tostitos simply': 'CHIPS'
    'potato crisps': 'CHIPS'
    'corn crisps': 'CHIPS'
    'potato chips': 'CHIPS'
    'tortilla chips': 'CHIPS'
    'goldfish': 'CRACKERS'
    'iced tea': 'FLAVORED DRINKS'
    'salsa dip': 'DIPS'
    'tostitos salsa': 'DIPS'
    'salsa mild': 'DIPS'
    'salsa chunky': 'DIPS'
    'salsa black': 'DIPS'
    'all purpose cleaner': 'CLEANERS'
    'shower': 'SHOWER SOAP'
    'seasoning': 'SPICES'
    'mac & cheese': 'PASTA'
    'american singles': 'CHEESE'
    'hot dogs': 'HOT DOGS'
    'shampoo': 'SHAMPOO'
    'vitamin water': 'FLAVORED DRINKS'
    'almond milk': 'FLAVORED DRINKS'
    'soy milk': 'FLAVORED DRINKS'
    'soymilk': 'FLAVORED DRINKS'
    'coconut milk': 'FLAVORED DRINKS'
    'sugar white': 'SUGAR'
    'bar': 'COOKIES'
    'pastry crisps': 'COOKIES'
    'french fries': 'FRENCH FRIES'
    'vinegar balsamic': 'SAUCES'
    'dressing': 'SAUCES'
    'pancakes': 'PANCAKES'
    'biscuits': 'SLICED BREAD'
    'rice krispies treats': 'COOKIES'
    'snack bites': 'COOKIES'
    'sour cream': 'SOUR CREAM'
    'fruit cup': 'FRESH FRUIT'
    'raisins': 'DRIED FRUIT'
    'cranberry sauce': 'SAUCES'
    'cool whip': 'SAUCES'
    'cooking stock': 'SOUP'
    'broth': 'SOUP'
    'baby oil original': 'PERSONAL HYGIENE'
    'baby powder original': 'PERSONAL HYGIENE'
    'burger': 'HAMBURGER'
